import { strict as assert } from "node:assert";
import { readFile, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { join } from "node:path";

async function main() {
  const runId = process.argv[2];
  assert(runId, "usage: smoke-micky-export.ts <runId-with-complete-micky-run>");

  const out = join("docs", `smoke-micky-export-${runId.slice(0, 8)}.md`);
  const result = spawnSync(
    "npx",
    [
      "tsx",
      "--conditions=import",
      "scripts/export-run-markdown.ts",
      "--run",
      runId,
      "--out",
      out,
    ],
    { stdio: "inherit", shell: true },
  );
  assert.equal(result.status, 0, "export command failed");

  const markdown = await readFile(out, "utf8");
  assert(markdown.includes("## Micky's Memo"));
  assert(markdown.includes("— MB ·"));
  assert(markdown.includes("This memo was generated by an AI system."));
  await rm(out, { force: true });
}

main().catch((e) => {
  console.error("smoke-micky-export failed:", e);
  process.exit(1);
});
